### ISSUE TITLE
使用python3 update.py --smbios gen 生成新的三码命令报错. 别的update.py的命令都可以使用

### ISSUE THREAD

**Issue by wsw-black** [xxxzc/xps15-9570-macos#105]
Failed trying to change dir to /Volumes/NO
Bad Pathname: No such file or directory
Failed trying to change dir to NAME/EFI/OC
Bad Pathname: No such file or directory
:: Generating sn, mlb and smuuid
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
curl: (6) Could not resolve host: NAME
chmod: /Volumes/NO: No such file or directory
chmod: NAME/EFI/OC/macserial: No such file or directory
/bin/sh: /Volumes/NO: No such file or directory
Traceback (most recent call last):
  File "update.py", line 570, in <module>
    gen_smbios()
  File "update.py", line 84, in inner
    return func(*args, **kwargs)
  File "update.py", line 354, in gen_smbios
    sn, _, mlb = shout(
  File "update.py", line 112, in shout
    return check_output(cmd, shell=True, encoding='utf-8').strip()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/Volumes/NO NAME/EFI/OC/macserial -m MacBookPro15,1 -g -n 1' returned non-zero exit status 127.

**Comment by xxxzc** [comment]
1. 不支持带空格的路径名，
2.  没代理可能下载不了macserial

用其他工具吧，或者从https://github.com/acidanthera/OpenCorePkg/releases 的包里找到macserial，运行 `macserial -m MacBookPro15,1 -g -n 1`
